### ISSUE TITLE
Invalid path error while connecting & creating the qvf file on the fly  with qlik core engine

### ISSUE THREAD

**Issue by rajasekar-d** [qlik-oss/halyard.js#81]
### Description
Invalid path error while connecting & creating the qvf file on the fly  with qlik core engine

### Steps to Reproduce

In the root folder, type the following:
1. npm install
2. npm run build

Go into the examples folder and type the following in the console:
1. npm install

##### Expected behavior

It should load airports.csv and create the qvf file on the fly.

**Note:** This works correctly when we connect with qliksense desktop instead of qlik core engine.

##### Actual behavior

Throws invalid path error
`
Table {
  connection: 
   FileConnection {
     path: 'D:\\QlikCore\\server-script\\data',
     connectionType: 'folder',
     fileExtension: 'csv',
     fileName: 'airports.csv' },
  name: 'Airports',
  fields: 
   [ { src: 'rowID', name: 'Id' },
     { src: 'Country', name: 'Country' } ],
  prefix: undefined,
  options: 
   { name: 'Airports',
     fields: [ [Object], [Object] ],
     delimiter: ',' } }
{ type: 'Connection Error',
  message: 'Invalid path',
  item: 
   FileConnection {
     path: 'D:\\QlikCore\\server-script\\data',
     connectionType: 'folder',
     fileExtension: 'csv',
     fileName: 'airports.csv',
     name: '069ff-8aecc-971dd-0ebf7eddde04' },
  qixError: { Error: Invalid path
    at Intercept.errorInterceptor (D:\QlikCore\server-script\node_modules\enigma.js\enigma.js:2305:19)
    at tryCatcher (D:\QlikCore\server-script\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\QlikCore\server-script\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\QlikCore\server-script\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\QlikCore\server-script\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\QlikCore\server-script\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\QlikCore\server-script\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\QlikCore\server-script\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\QlikCore\server-script\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5) code: 4, parameter: 'Invalid path' } }

`

##### Library
```
* Node.js 
* Browser
* Docker Community edition
```
##### Operating system
```
* Windows 10
```
##### Qlik Sense
```
[ ] Qlik Core Engine
```
### Versions

* Node.js: v9.10.1
* Browser: 62.0.3202.62 (Official Build) (64-bit)
* Docker Community edition: 18.03.0-ce-win59 (16762)

**Comment by sublibra** [comment]
Seems to be a an issue folder mounts in docker. It works on Max and Ubuntu subsystem running on Windows 10. I will see if I can find a workaround.

**Comment by sublibra** [comment]
What shell do you run in? Many people, including me, uses mingw64 (installed with git for Windows). There are many issues connected to running docker in this but a common workaround is to run 
**MSYS_NO_PATHCONV=1** before executing the docker commands. The will ensure that the shell doesn't try to convert the paths to windows paths and let docker do this.

In this case we would have
MSYS_NO_PATHCONV=1 ACCEPT_EULA=yes docker-compose up -d
which seems to work in my installation.

**Comment by rajasekar-d** [comment]
After "reset credentials" and sharing the drive again under docker settings is working fine.
